var elements = [
		{
			name: "Hydrogen",
			espName: "Hidrógeno",
      symbol: "H",
			id: 1,
		},
    {
      name: "Helium",
      espName: "Hélio",
      symbol: "He",
      id: 2,
    },
    {
      name: "Lithium",
      espName: "Lítio",
      symbol: "Li",
      id: 3,
    },
    {
      name: "Beryllium",
      espName: "Berílio",
      symbol: "Be",
      id: 4,
    },
    {
      name: "Boron",
      espName: "Boro",
      symbol: "B",
      id: 5,
    },
    {
      name: "Carbon",
      espName: "Carbono",
      symbol: "C",
      id: 6,
    },
    {
      name: "Nitrogen",
      espName: "Nitrógeno",
      symbol: "N",
      id: 7,
    },
    {
      name: "Oxygen",
      espName: "Oxígeno",
      symbol: "O",
      id: 8,
    },
    {
      name: "Fluorine",
      espName: "Flúor",
      symbol: "F",
      id: 9,
    },
    {
      name: "Neon",
      espName: "Neón",
      symbol: "Ne",
      id: 10,
    },
    {
      name: "Sodium",
      espName: "Sodio",
      symbol: "Na",
      id: 11,
    },
    {
      name: "Magnesium",
      espName: "Magnesio",
      symbol: "Mg",
      id: 12,
    },
    {
      name: "Aluminium",
      espName: "Alumínio",
      symbol: "Al",
      id: 13,
    },
    {
      name: "Silicon",
      espName: "Silico",
      symbol: "Si",
      id: 14,
    },
    {
      name: "Phosphorus",
      espName: "Fósforo",
      symbol: "P",
      id: 15,
    },
    {
      name: "Sulfur",
      espName: "Azufre",
      symbol: "S",
      id: 16,
    },
    {
      name: "Chlorine",
      espName: "Cloro",
      symbol: "Cl",
      id: 17,
    },
    {
      name: "Argon",
      espName: "Argón",
      symbol: "Ar",
      id: 18,
    },
    {
      name: "Potassium",
      espName: "Potasio",
      symbol: "K",
      id: 19,
    },
    {
      name: "Calcium",
      espName: "Calcio",
      symbol: "Ca",
      id: 20,
    },
    {
      name: "Scandium",
      espName: "Escandio",
      symbol: "Sc",
      id: 21,
    },
    {
      name: "Titanium",
      espName: "Titanio",
      symbol: "Ti",
      id: 22,
    },
    {
      name: "Vanadium",
      espName: "Vanadio",
      symbol: "V",
      id: 23,
    },
    {
      name: "Chromium",
      espName: "Cromo",
      symbol: "Cr",
      id: 24,
    },
    {
      name: "Manganese",
      espName: "Manganesio",
      symbol: "Mn",
      id: 25,
    },
    {
      name: "Iron",
      espName: "Hierro",
      symbol: "Fe",
      id: 26,
    },
    {
      name: "Cobalt",
      espName: "Cobalto",
      symbol: "Co",
      id: 27,
    },
    {
      name: "Nickel",
      espName: "Níquel",
      symbol: "Ni",
      id: 28,
    },
    {
      name: "Copper",
      espName: "Cobre",
      symbol: "Cu",
      id: 29,
    },
    {
      name: "Zinc",
      espName: "Zinc",
      symbol: "Zn",
      id: 30,
    },
    {
      name: "Gallium",
      espName: "Galio",
      symbol: "Ga",
      id: 31,
    },
    {
      name: "Germanium",
      espName: "Germánio",
      symbol: "Ge",
      id: 32,
    },
    {
      name: "Arsenic",
      espName: "Arsénico",
      symbol: "As",
      id: 33,
    },
    {
      name: "Selenium",
      espName: "Selenio",
      symbol: "Se",
      id: 34,
    },
    {
      name: "Bromine",
      espName: "Bromo",
      symbol: "Br",
      id: 35,
    },
    {
      name: "Krypton",
      espName: "Criptón",
      symbol: "Kr",
      id: 36,
    },
		{
			name: "Rubidium",
			espName: "Rubídio",
			symbol: "Rb",
			id: 37,
		},
		{
			name: "Strontium",
			espName: "Estroncio",
			symbol: "Sr",
			id: 38,
		},
		{
			name: "Yttrium",
			espName: "Itrio",
			symbol: "Yt",
			id: 39,
		},
		{
			name: "Zirconium",
			espName: "Circonio",
			symbol: "Zr",
			id: 40,
		},
		{
			name: "Niobium",
			espName: "Niobio",
			symbol: "Nb",
			id: 41,
		},
		{
			name: "Molybdenum",
			espName: "Molibdeno",
			symbol: "Mo",
			id: 42,
		},
		{
			name: "Technetium",
			espName: "Tecnecio",
			symbol: "Tc",
			id: 43,
		},
		{
			name: "Ruthenium",
			espName: "Rutenio",
			symbol: "Ru",
			id: 44,
		},
		{
			name: "Silver",
			espName: "Plata",
			symbol: "Ag",
			id: 47,
		},
		{
			name: "Tin",
			espName: "Estaño",
			symbol: "Sd",
			id: 50,
		},
		{
			name: "Xenon",
			espName: "Xenón",
			symbol: "Xe",
			id: 54,
		},
		{
			name: "Tungsten",
			espName: "Wolframio",
			symbol: "W",
			id: 74,
		},
		{
			name: "Gold",
			espName: "Oro",
			symbol: "Au",
			id: 79,
		},
		{
			name: "Mercury",
			espName: "Mercurio",
			symbol: "Hg",
			id: 80,
		},
		{
			name: "Lead",
			espName: "Plomo",
			symbol: "Pb",
			id: 82,
		},
		{
			name: "Californium",
			espName: "Californio",
			symbol: "Cf",
			id: 98,
		},
		{
			name: "Neptunium",
			espName: "Neptunio",
			symbol: "Np",
			id: 93,
		},
		{
			name: "Plutonium",
			espName: "Plutonio",
			symbol: "Pu",
			id: 94,
		},
		{
			name: "Iodine",
			espName: "Yodo",
			symbol: "I",
			id: 53,
		},
		{
			name: "Antimony",
			espName: "Antimonio",
			symbol: "Sb",
			id: 51,
		},
];

var fakeElements = [
	{
		name: "Blahium",
		espName: "Falsónio",
		symbol: "Bs",
		id: 100,
	},
	{
		name: "Fakeium",
		espName: "Mentiráneo",
		symbol: "Bs",
		id: 101,
	},
	{
		name: "Twitterium",
		espName: "Twitterio",
		symbol: "Bs",
		id: 102,
	},
	{
		name: "Crazium",
		espName: "Lóconio",
		symbol: "Bs",
		id: 103,
	},
	{
		name: "Fakeium",
		espName: "Mentiráneo",
		symbol: "Bs",
		id: 101,
	},
	{
		name: "Psychonium",
		espName: "Psicópatanio",
		symbol: "Bs",
		id: 102,
	},
	{
		name: "Insanium",
		espName: "Insanonio",
		symbol: "Bs",
		id: 103,
	},
]
