var elements = [
		{
			name: "Hydrogen",
			espName: "",
      symbol: "H",
			id: 1,
		},
    {
      name: "Helium",
      espName: "",
      symbol: "He",
      id: 2,
    },
    {
      name: "Lithium",
      espName: "",
      symbol: "Li",
      id: 3,
    },
    {
      name: "Beryllium",
      espName: "",
      symbol: "Be",
      id: 4,
    },
    {
      name: "Boron",
      espName: "",
      symbol: "B",
      id: 5,
    },
    {
      name: "Carbon",
      espName: "",
      symbol: "C",
      id: 6,
    },
    {
      name: "Nitrogen",
      espName: "",
      symbol: "N",
      id: 7,
    },
    {
      name: "Oxygen",
      espName: "",
      symbol: "O",
      id: 8,
    },
    {
      name: "Fluorine",
      espName: "",
      symbol: "F",
      id: 9,
    },
    {
      name: "Neon",
      espName: "",
      symbol: "Ne",
      id: 10,
    },
    {
      name: "Sodium",
      espName: "",
      symbol: "Na",
      id: 11,
    },
    {
      name: "Magnesium",
      espName: "",
      symbol: "Mg",
      id: 12,
    },
    {
      name: "Aluminium",
      espName: "",
      symbol: "Al",
      id: 13,
    },
    {
      name: "Silicon",
      espName: "",
      symbol: "Si",
      id: 14,
    },
    {
      name: "Phosphorus",
      espName: "",
      symbol: "P",
      id: 15,
    },
    {
      name: "Sulfur",
      espName: "",
      symbol: "S",
      id: 16,
    },
    {
      name: "Chlorine",
      espName: "",
      symbol: "Cl",
      id: 17,
    },
    {
      name: "Argon",
      espName: "",
      symbol: "Ar",
      id: 18,
    },
    {
      name: "Potassium",
      espName: "",
      symbol: "K",
      id: 19,
    },
    {
      name: "Calcium",
      espName: "",
      symbol: "Ca",
      id: 20,
    },
    {
      name: "Scandium",
      espName: "",
      symbol: "Sc",
      id: 21,
    },
    {
      name: "Titanium",
      espName: "",
      symbol: "Ti",
      id: 22,
    },
    {
      name: "Vanadium",
      espName: "",
      symbol: "V",
      id: 23,
    },
    {
      name: "Chromium",
      espName: "",
      symbol: "Cr",
      id: 24,
    },
    {
      name: "Manganese",
      espName: "",
      symbol: "Mn",
      id: 25,
    },
    {
      name: "Iron",
      espName: "",
      symbol: "Fe",
      id: 26,
    },
    {
      name: "Cobalt",
      espName: "",
      symbol: "Co",
      id: 27,
    },
    {
      name: "Nickel",
      espName: "",
      symbol: "Ni",
      id: 28,
    },
    {
      name: "Copper",
      espName: "",
      symbol: "Cu",
      id: 29,
    },
    {
      name: "Zinc",
      espName: "",
      symbol: "Zn",
      id: 30,
    },
    {
      name: "Gallium",
      espName: "",
      symbol: "Ga",
      id: 31,
    },
    {
      name: "Germanium",
      espName: "",
      symbol: "Ge",
      id: 32,
    },
    {
      name: "Arsenic",
      espName: "",
      symbol: "As",
      id: 33,
    },
    {
      name: "Selenium",
      espName: "",
      symbol: "Se",
      id: 34,
    },
    {
      name: "Bromine",
      espName: "",
      symbol: "Br",
      id: 35,
    },
    {
      name: "Krypton",
      espName: "",
      symbol: "Kr",
      id: 36,
    },
    {
      name: "BlahBlahium",
      espName: "",
      symbol: "Ar",
      id: 37,
    },
    {
      name: "Fakium",
      espName: "",
      symbol: "Ar",
      id: 38,
    },

];
